//! Snapshot tests using the Unmix.xcodeproj as a real-world baseline.
//!
//! The expected outputs were generated by running the TypeScript library
//! against the same input files. Any change that causes these tests to fail
//! indicates a behavioral divergence from the TypeScript implementation.

mod common;

use anyhow::Result;

use common::{canonicalize_json, normalize_newlines, read_fixture};

// ---------------------------------------------------------------------------
// JSON (pbxproj)
// ---------------------------------------------------------------------------

#[test]
fn unmix_json_parse_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/project.pbxproj")?;
    let expected: serde_json::Value =
        serde_json::from_str(&read_fixture("fixtures/unmix/project.parse.json")?)?;

    let rs = xcode::json::parse(&input)?;

    assert_eq!(
        canonicalize_json(&expected),
        canonicalize_json(&rs),
        "Unmix pbxproj parse diverges from TS baseline"
    );

    Ok(())
}

#[test]
fn unmix_json_build_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/project.pbxproj")?;
    let expected_build = read_fixture("fixtures/unmix/project.build.pbxproj")?;

    let parsed = xcode::json::parse(&input)?;
    let rs_built = xcode::json::build(&parsed);

    assert_eq!(
        normalize_newlines(&expected_build),
        normalize_newlines(&rs_built),
        "Unmix pbxproj build diverges from TS baseline"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Scheme
// ---------------------------------------------------------------------------

#[test]
fn unmix_scheme_parse_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/UnmixMac.xcscheme")?;
    let expected: serde_json::Value =
        serde_json::from_str(&read_fixture("fixtures/unmix/UnmixMac.scheme_parse.json")?)?;

    let rs = xcode::scheme::parse(&input)?;
    let rs_json = serde_json::to_value(&rs)?;

    // Compare key fields that the TS oracle returns
    assert_eq!(
        expected.get("version").and_then(|v| v.as_str()),
        rs.version.as_deref(),
        "scheme version mismatch"
    );
    assert_eq!(
        expected.get("lastUpgradeVersion").and_then(|v| v.as_str()),
        rs.last_upgrade_version.as_deref(),
        "scheme lastUpgradeVersion mismatch"
    );

    // Full structural comparison
    assert_eq!(
        canonicalize_json(&expected),
        canonicalize_json(&rs_json),
        "Unmix scheme parse diverges from TS baseline"
    );

    Ok(())
}

#[test]
fn unmix_scheme_build_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/UnmixMac.xcscheme")?;
    let expected_build = read_fixture("fixtures/unmix/UnmixMac.scheme_build.xcscheme")?;

    let rs = xcode::scheme::parse(&input)?;
    let rs_built = xcode::scheme::build(&rs);

    assert_eq!(
        normalize_newlines(&expected_build),
        normalize_newlines(&rs_built),
        "Unmix scheme build diverges from TS baseline"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Scheme Management
// ---------------------------------------------------------------------------

#[test]
fn unmix_scheme_management_parse_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/xcschememanagement.plist")?;
    let expected: serde_json::Value = serde_json::from_str(&read_fixture(
        "fixtures/unmix/xcschememanagement.scheme_mgmt_parse.json",
    )?)?;

    let rs = xcode::scheme::parse_management(&input)?;
    let rs_json = serde_json::to_value(&rs)?;

    assert_eq!(
        canonicalize_json(&expected),
        canonicalize_json(&rs_json),
        "Unmix scheme management parse diverges from TS baseline"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Workspace
// ---------------------------------------------------------------------------

#[test]
fn unmix_workspace_parse_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/contents.xcworkspacedata")?;
    let expected: serde_json::Value =
        serde_json::from_str(&read_fixture("fixtures/unmix/contents.workspace_parse.json")?)?;

    let rs = xcode::workspace::parse(&input)?;
    let rs_json = serde_json::to_value(&rs)?;

    assert_eq!(
        canonicalize_json(&expected),
        canonicalize_json(&rs_json),
        "Unmix workspace parse diverges from TS baseline"
    );

    Ok(())
}

#[test]
fn unmix_workspace_build_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/contents.xcworkspacedata")?;
    let expected_build =
        read_fixture("fixtures/unmix/contents.workspace_build.xcworkspacedata")?;

    let rs = xcode::workspace::parse(&input)?;
    let rs_built = xcode::workspace::build(&rs);

    assert_eq!(
        normalize_newlines(&expected_build),
        normalize_newlines(&rs_built),
        "Unmix workspace build diverges from TS baseline"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Breakpoints
// ---------------------------------------------------------------------------

#[test]
fn unmix_breakpoints_parse_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/Breakpoints_v2.xcbkptlist")?;
    let expected: serde_json::Value = serde_json::from_str(&read_fixture(
        "fixtures/unmix/Breakpoints_v2.breakpoints_parse.json",
    )?)?;

    let rs = xcode::breakpoints::parse(&input)?;
    let rs_json = serde_json::to_value(&rs)?;

    assert_eq!(
        canonicalize_json(&expected),
        canonicalize_json(&rs_json),
        "Unmix breakpoints parse diverges from TS baseline"
    );

    Ok(())
}

#[test]
fn unmix_breakpoints_build_matches_ts_snapshot() -> Result<()> {
    let input = read_fixture("fixtures/unmix/Breakpoints_v2.xcbkptlist")?;
    let expected_build =
        read_fixture("fixtures/unmix/Breakpoints_v2.breakpoints_build.xcbkptlist")?;

    let rs = xcode::breakpoints::parse(&input)?;
    let rs_built = xcode::breakpoints::build(&rs);

    assert_eq!(
        normalize_newlines(&expected_build),
        normalize_newlines(&rs_built),
        "Unmix breakpoints build diverges from TS baseline"
    );

    Ok(())
}
